name: AndroidBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
      - with :
          name: Android CICD Demo.apk
          path: app/build/output/apk/debug/app-debug.apk

